# Generated by Django 3.2.7 on 2021-09-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_myuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='client',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='sales_contact',
        ),
        migrations.RemoveField(
            model_name='event',
            name='client',
        ),
        migrations.RemoveField(
            model_name='event',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='event',
            name='support',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
